version: 2.0
jobs:
  dev-deploy:
    docker:
      - image: quay.io/pantheon-public/build-tools-ci:nodejs
    working_directory: ~/NEDCamp/nedcamp
    parallelism: 1
    shell: /bin/bash --login
    steps:
      - run: git config --global user.email "nic@nlightened.net"
      - run: git config --global user.name "Nic"
      - checkout
      - run: terminus auth:login --machine-token=$TERMINUS_TOKEN
      - run: composer install
      - run: rm ~/NEDCamp/nedcamp/.gitignore
      - run: cp ~/NEDCamp/nedcamp/.circleci/gitignore_production ~/NEDCamp/nedcamp/.gitignore
      - run: git add .
      - run: echo -e "Host codeserver.dev.1e9ab33c-01d3-42bd-bb42-5008333172a3.drush.in\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: ssh-keyscan codeserver.dev.1e9ab33c-01d3-42bd-bb42-5008333172a3.drush.in >> ~/.ssh/known_hosts
      - run: echo -e "Host appserver.dev.1e9ab33c-01d3-42bd-bb42-5008333172a3.drush.in\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: ssh-keyscan appserver.dev.1e9ab33c-01d3-42bd-bb42-5008333172a3.drush.in >> ~/.ssh/known_hosts
      - run: terminus env:wake nedcamp.dev
      - run: git commit -m "add build files to branches to push to Pantheon"
      - run: git remote add pantheon ssh://codeserver.dev.1e9ab33c-01d3-42bd-bb42-5008333172a3@codeserver.dev.1e9ab33c-01d3-42bd-bb42-5008333172a3.drush.in:2222/~/repository.git
      - run: if [[ $CIRCLE_BRANCH == 'master' ]] ; then git push --force  pantheon master:master ; fi
      - run: sleep 120
      - run: terminus env:clear-cache nedcamp.dev
      - run: terminus -n drush nedcamp.dev -- updb --yes
      - run: terminus -n drush nedcamp.dev -- config-import --yes
      - run: terminus env:clear-cache nedcamp.dev
workflows:
  version: 2
  build-deploy-dev:
    jobs:
      - dev-deploy:
          filters:
            branches:
              only: master
