definitions:
  contact__site_page:
    weight: -46
    menu_name: footer
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    weight: -49
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
  user__logout:
    menu_name: main
    parent: ''
    weight: 10
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
