api_key: 629c62b6690ecead6181ab8e5d94c33d-us5
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
enable_connected: true
connected_id: null
connected_paths: null
