site_key: 6LdLsWIUAAAAAM8kUvjlHNgXvYqjPlq3wvQxi70q
secret_key: 6LdLsWIUAAAAAHuS6bb_g_bdLY_HjbANCYl7SCQ5
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: true
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
