site_key: 6Lc5IAUTAAAAAMPdien8oTG_cHmoPaMXqagpY40U
secret_key: 6Lc5IAUTAAAAAJ6bQ8a239IiBDQstuiJvFVqH0Ri
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: true
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
